### PR TITLE
Collab/calcsize

### PR DESCRIPTION
**Pull request by odiazib**
This PR contains necessary inputs and baseline reference files for the validation of  `calcsize` in MAM4xx (eagles-project/mam4xx#72). We have added validation tests for several functions in `calcsize`; however, several of they yaml and input files will need to be updated with the forthcoming corresponding versions produced by mam4/e3sm. Currently, the following cases produced by mam4/e3sm are included: `calcsize_e3sm`, `calcsize_sub_ts_378`, and `calcsize_sub_ts_379`. Further, we add a script `mam_x_validation/scripts/compare_mam4xx_mam4.py` to compare the python output files from mam4 and mam4xx.

### CODE REVIEW

**Comment by mjs271** [comment]
***Note*** that this should probably be merged before eagles-project/mam4xx#72

**Review by mjs271 — APPROVED** [review]
🕺🏻

**Review by jeff-cohere — APPROVED** [review]
Cool. I'm curious--are you planning to merge some of these datasets with the new tool? This can be done down the line, of course.

**Review by pbosler — APPROVED** [review]

**Review by singhbalwinder — APPROVED** [review]
Looks great! Would it possible to post the test output here?

**Pull request merged**
